ceph_istio_enabled: true
ceph_domain: ceph.<path:ocivault#mosip_domain#latest | base64decode>

rook-ceph-cluster:
  toolbox:
    enabled: true
    tolerations: 
    - key: "node-role.kubernetes.io/rook-node"
      operator: "Exists"
      effect: "NoSchedule"
    affinity: 
      oke.oraclecloud.com/pool.name: rook
  cephClusterSpec:
    dashboard:
      enabled: true
      ssl: false
    mgr:
      # When higher availability of the mgr is needed, increase the count to 2.
      # In that case, one mgr will be active and one in standby. When Ceph updates which
      # mgr is active, Rook will update the mgr services to match the active mgr.
      count: 2
      allowMultiplePerNode: false
      modules:
        - name: rook
          enabled: true
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: oke.oraclecloud.com/pool.name
                  operator: In
                  values:
                  - rook
        podAffinity:
          oke.oraclecloud.com/pool.name: rook
        tolerations:
        - key: "node-role.kubernetes.io/rook-node"
          operator: "Exists"
          effect: "NoSchedule"